### ISSUE TITLE
can't work,Pls tell me why?

### ISSUE THREAD

**Issue by woodgreat** [jupyterlite/javascript-kernel#16]
![20240704190405](https://github.com/jupyterlite/javascript-kernel/assets/38380995/0b10e0f8-cb2d-4a31-af30-a9811ce489b5)

**Comment by martinRenou** [comment]
The JavaScript kernel runs in a web worker, where `console` does not exist

**Comment by woodgreat** [comment]
so，how to do for it ?I need the answer .thank you!

**Comment by DerThorsten** [comment]
> so，how to do for it ?I need the answer .thank you!

you can try xeus-javascript https://github.com/jupyter-xeus/xeus-javascript, console.log works there.

@martinRenou `console.log` usually does work in a worker....

**Comment by woodgreat** [comment]
thanks!

**Comment by woodgreat** [comment]
> The JavaScript kernel runs in a web worker, where `console` does not exist

how to start the web worker?

**Comment by jtpio** [comment]
@woodgreat according to the screenshot it looks like you are trying to run JavaScript code in a regular JupyterLab with a Python kernel? (since there is the extension manager panel on the left).

I get the same error when trying to execute the same code snippet with ipykernel:

![image](https://github.com/jupyterlite/javascript-kernel/assets/591645/59daf45a-49a9-4e04-b24e-c93e616c43a2)

**Comment by jtpio** [comment]
@woodgreat if you want to use the JavaScript kernel, you can for example open https://jupyterlite.github.io/demo/lab/index.html in a browser tab, and make sure you have selected "JavaScript (Web Worker)" as the kernel:

![image](https://github.com/jupyterlite/javascript-kernel/assets/591645/68281440-fc96-47e3-9038-92f9dae20925)

Closing as answered, but don't hesitate to open a new issue if you have more questions!

**Comment by martinRenou** [comment]
> @martinRenou console.log usually does work in a worker

I assumed it would not work, sorry for the confusion!

The Python traceback formatting should have been another hint 👀

**Comment by woodgreat** [comment]
Thank YOU ! finally，i know why i can not use it .i should use jupyterlite instead of the lab ,so i keep learning of it, thank you.
